on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t prisma_distroless:latest .

      - name: Run build container
        run: docker run --rm prisma_distroless:latest
